/*
 * MainFrame.java
 *
 * Created on Feb 9, 2012, 12:07:46 AM
 */
package alarmclock.view;

import alarmclock.models.FavoriteAlarm;
import alarmclock.services.AlarmStarter;
import alarmclock.services.ProcessStarter;
import alarmclock.services.PropertiesLoader;
import alarmclock.models.SetAlarm;
import alarmclock.services.FavoriteAlarmService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Comparator;
import java.util.SortedSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingWorker;
import org.joda.time.DateTime;
import org.joda.time.LocalTime;

/**
 * The MainFrame displays the data and responds to events.  Because this is
 * written in the Swing framework, it must also be the Controller, that is,
 * the part that responds to user input and changes the View.  More modern
 * UI frameworks separate out the Controller and the View aspects.
 * 
 * This class Does Something.
 * @author Gordon
 */
public class MainFrame extends javax.swing.JFrame {

    //<editor-fold desc="fields">    
    /**
     * This is the sorted collection we are using to hold the current alarm panels.
     * We enforce the ordering by providing it with a Comparator.  This Comparator
     * specifies that two AlarmPanels should be compared by the Time of their Alarms.
     * When the SortedSet wants to sort itself it will call the compare method
     * of this comparator.
     */
    private SortedSet<AlarmPanel> alarms = new java.util.TreeSet<AlarmPanel>(
            new Comparator<AlarmPanel>(){
                @Override
                public int compare(AlarmPanel o1, AlarmPanel o2) {
                    return o1.getAlarm().getTime().compareTo(o2.getAlarm().getTime());
                }
            });
    
    /**
     * This is simply a File choosing dialog that we can pop up when the user
     * hits the choose button.
     */
    private final JFileChooser fileChooser = new JFileChooser();
    
    //this timer is just going to invoke Update to update the display clock, it's not
    //going to do any important timing, all that will happen in TimerAlarmStarter
    javax.swing.Timer updateTimer;
    //</editor-fold>
    
    //<editor-fold desc="services">
    /*
     * Here are all the injected services.  These services will be used by
     * the MainFrame controller to perform actions, namely creating saving and 
     * setting Alarms.  These service objects are all objects that Do Something.
     * They are not created by the MainFrame itself, but rather are injected
     * so that the main frame can be more easily tested.
     */
    
    private ProcessStarter processStarter;
    public ProcessStarter getProcessStarter() {
        return processStarter;
    }

    public void setProcessStarter(ProcessStarter pStarter) {
        this.processStarter = pStarter;
    }
    
    private AlarmStarter alarmStarter;
    public void setAlarmStarter(AlarmStarter starter){
        this.alarmStarter = starter;
    }
    
    private FavoriteAlarmService favoritesService;
    public void setFavoritesService(FavoriteAlarmService favoritesService){
        this.favoritesService = favoritesService;
    }
    //</editor-fold>
    
    /** The MainFrame constructor
     *  just sets up default stuff the frame needs in order to run
     */
    public MainFrame() {
        initComponents();
        
        //This just tells the frame to exit the program when the main frame closes.
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called to initialize the class AFTER all the injected
     * properties have been set.  We cannot call this in the constructor because
     * we require the injected services, but we must do this before we do anything
     * with the MainFrame.
     */
    public void init(){
                
        this.loadFavoriteAlarms();
        
        //Set up the timer to call update every 1 second
        updateTimer = new javax.swing.Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                MainFrame.this.update();
            }
        });
        updateTimer.start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setSpinner = new javax.swing.JSpinner();
        exePath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        setAlarmsPanel = new javax.swing.JPanel();
        chooseButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        CurrentTime = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        favoritesPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setSpinner.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        setSpinner.setModel(new javax.swing.SpinnerDateModel());
        setSpinner.setEditor(new javax.swing.JSpinner.DateEditor(setSpinner, "h:mm a"));

        exePath.setMinimumSize(new java.awt.Dimension(200, 20));
        exePath.setPreferredSize(new java.awt.Dimension(200, 20));
        exePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exePathActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 100));

        setAlarmsPanel.setMaximumSize(new java.awt.Dimension(65535, 65535));
        setAlarmsPanel.setLayout(new javax.swing.BoxLayout(setAlarmsPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(setAlarmsPanel);

        chooseButton.setText("Choose");
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        errorText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 51, 51));
        errorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        CurrentTime.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        CurrentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentTime.setText("12:00 AM");

        favoritesPanel.setLayout(new javax.swing.BoxLayout(favoritesPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(favoritesPanel);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                            .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setButton, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(exePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(setSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chooseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(testButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                    .addComponent(CurrentTime, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exePath, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(setButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void exePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exePathActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_exePathActionPerformed

private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
    //This is the event handler for when the choose button is clicked
    
    this.errorText.setText("");
    
    //Open the file chooser dialog
    int returnVal = fileChooser.showOpenDialog(this);
    
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        //If the user approved a file, get it and set the text.
        File file = fileChooser.getSelectedFile();
        
        //perform a little processing on the path
        String[] path = file.getPath().split("\\\\");
        StringBuilder sb = new StringBuilder();
        int i;
        for(i = 0; i < path.length-1; i++){
            if(path[i].contains(" ")){
                //gotta add quotes if part of the path contains spaces
                sb.append("\"").append(path[i]).append("\"");
            }
            else
                sb.append(path[i]);
            
            sb.append("\\");
        }
        if(path[i].contains(".")){
            String[] splitOnDot = path[i].split("\\.");
            if(splitOnDot[0].contains(" "))
                //gotta add quotes if part of the path contains spaces
                sb.append("\"").append(splitOnDot[0]).append("\"");
            else
                sb.append(splitOnDot[0]);
            sb.append(".").append(splitOnDot[1]);
        }
        else
            sb.append(path[i]);
        
        //set the text box to the new value
        this.exePath.setText(sb.toString());
    }
}//GEN-LAST:event_chooseButtonActionPerformed

private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
    this.errorText.setText("");
    
    //Set a new alarm
    DateTime almTime = new DateTime(this.setSpinner.getValue());
    almTime = new DateTime().millisOfDay().setCopy(almTime.getMillisOfDay());
    
    if(almTime.isBeforeNow())
        //they probably meant tomorrow
        almTime = almTime.dayOfMonth().addToCopy(1);
    
    this.setAlarm(almTime, this.exePath.getText());
    
}//GEN-LAST:event_setButtonActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    //Save a new favorite alarm
    this.setFavorite(new DateTime(this.setSpinner.getValue()), this.exePath.getText());
}//GEN-LAST:event_saveButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        this.errorText.setText("");
        
        String path = this.exePath.getText();
        
        if(path == null || path.trim().isEmpty()){
            this.errorText.setText("No path to test");
            return;
        }
        
        try {
            //execute the given file immediately
            this.processStarter.runFile(path);
            
        } catch (IOException ex) {
            //there was an error, show it in the error window
            this.errorText.setText(ex.toString());
        }
    }//GEN-LAST:event_testButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentTime;
    private javax.swing.JButton chooseButton;
    private javax.swing.JLabel errorText;
    private javax.swing.JTextField exePath;
    private javax.swing.JPanel favoritesPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel setAlarmsPanel;
    private javax.swing.JButton setButton;
    private javax.swing.JSpinner setSpinner;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables


    private void update(){
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                DateTime now = new DateTime();
                MainFrame.this.CurrentTime.setText(now.toString("MMM d, yyyy h:mm:ss a"));                 
            }
        });     
        
    }
    
    private void startFavoriteAlarm(FavoriteAlarm alarm){
                   
        SetAlarm setAlarm = this.favoritesService.CreateAlarm(alarm);
        
        this.setAlarm(setAlarm);
    }
    
    private SetAlarm setAlarm(DateTime time, String exePath){
        final SetAlarm alm = this.alarmStarter.CreateAlarm(time, exePath);

        setAlarm(alm);
        
        return alm;
    }
    
    private SetAlarm setAlarm(final SetAlarm alm){
        final AlarmPanel panel = new AlarmPanel();
        panel.setAlarm(alm);
        try {
            this.alarmStarter.StartAlarm(alm, new Runnable(){
                @Override
                public void run() {
                    MainFrame.this.onAlarmFinished(panel, alm);
                }                
            });
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            this.errorText.setText("Can't start alarm: " + ex.toString());
            return null;
        }
        
        panel.addCancelAlarmListener(new AlarmPanel.CancelAlarmListener(){
            @Override
            public void alarmCancelled(SetAlarm alarm) {
                MainFrame.this.alarms.remove(panel);
                MainFrame.this.updateAlarmsPanel();                            
                panel.removeCancelAlarmListener(this);
            }
            
        });
        
        this.alarms.add(panel);
        
        panel.setVisible(true);
        this.updateAlarmsPanel();
        
        return alm;
    }

    private void onAlarmFinished(final AlarmPanel panel, final SetAlarm alm){
        try {
            this.processStarter.runFile(alm.getPath());
        } catch (final IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    
            java.awt.EventQueue.invokeLater(new Runnable(){
                @Override
                public void run() {
                    MainFrame.this.errorText.setText("Could not start " + 
                            alm.getPath() + " because: " +
                            ex.getMessage());
                }        
            });
            return;
        }
        
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                MainFrame.this.alarms.remove(panel);
                MainFrame.this.updateAlarmsPanel();
            }
        });     
    }
    
    private FavoriteAlarmPanel setFavorite(DateTime time, String exePath){
        if(exePath.trim().isEmpty())
            return null;
        
        if(time == null)
            return null;
        
        FavoriteAlarm alm = this.favoritesService.SaveFavorite(time.toLocalTime(), exePath);
        
        final FavoriteAlarmPanel fave = new FavoriteAlarmPanel(alm);
        this.hookupFavorite(fave);
        this.favoritesPanel.add(fave);
        fave.setVisible(true);
        this.favoritesPanel.repaint();
        
        return fave;
    }
    
    private void hookupFavorite(final FavoriteAlarmPanel fave){
        fave.addFavoriteAlarmListener(new FavoriteAlarmPanel.FavoriteAlarmListener() {

            @Override
            public void RemoveFavorite(FavoriteAlarm favorite) {
                MainFrame.this.favoritesService.DeleteFavorite(favorite);
                MainFrame.this.favoritesPanel.remove(fave);
                MainFrame.this.favoritesPanel.repaint();
                MainFrame.this.repaint();
            }

            @Override
            public void StartFavorite(FavoriteAlarm favorite) {
                MainFrame.this.startFavoriteAlarm(favorite);
            }
        });
    }
    
    private void updateAlarmsPanel(){
        this.setAlarmsPanel.removeAll();
        for(AlarmPanel p : this.alarms){
            this.setAlarmsPanel.add(p);            
        }
        this.setAlarmsPanel.repaint();
    }
    
    private void loadFavoriteAlarms(){
                
        
        for(FavoriteAlarm alm : this.favoritesService.getFavorites()){
            FavoriteAlarmPanel almPanel = new FavoriteAlarmPanel(alm);
            
            this.hookupFavorite(almPanel);
            this.favoritesPanel.add(almPanel);
            almPanel.setVisible(true);            
        }
        
        this.favoritesPanel.repaint();
    }
}
