/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlarmPanel.java
 *
 * Created on Feb 9, 2012, 12:20:57 AM
 */
package alarmclock;

import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

/**
 *
 * @author Gordon
 */
public class AlarmPanel extends javax.swing.JPanel {

    private SetAlarm alarm;
    public SetAlarm getAlarm(){
        return alarm;
    }
    public void setAlarm(SetAlarm alarm){
        this.alarm = alarm;
        
        this.Update();
    }
    
    /** Creates new form AlarmPanel */
    public AlarmPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTime = new javax.swing.JLabel();
        exePath = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setTime.setText("12:00 AM");

        exePath.setText("www.pandora.com");

        cancelButton.setText("cancel");
        cancelButton.setPreferredSize(new java.awt.Dimension(63, 20));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setTime, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(setTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exePath))
            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    if(this.alarm != null){
        this.alarm.cancel();
    }
        
}//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel exePath;
    private javax.swing.JLabel setTime;
    // End of variables declaration//GEN-END:variables

    private static DateTimeFormatter formatter = DateTimeFormat.forPattern("h:mm a d MMM, yyyy");
    public void Update(){
        this.exePath.setText(alarm.getPath());
        this.setTime.setText(alarm.getTime().toString(formatter));
    }
}
